### ISSUE TITLE
Spyral Notebook - Save

### ISSUE THREAD

**Issue by kwsherwood** [voyanttools/Voyant#3]
Saving of a multi-part, Spyral notebook (i.e. once modified)  seems to hang indefinitely. 

(Tried with Firefox and Chrome).

**Comment by ajmacdonald** [comment]
Hi Kenneth, thanks for reporting this.
Spyral is currently under heavy development so expect things not to work. That said, you should be able to save.
I require more detail to investigate your issue however. Can you try with the developer tools open and tell me what error messages appear in the console when you try to save?

**Comment by kwsherwood** [comment]
Thanks for the follow-up.

Here's a screen capture of the console:


__________________________________

Kenneth Sherwood
www.sherwoodweb.org

**Comment by ajmacdonald** [comment]
Unfortunately the screen capture didn't come through.

**Comment by kwsherwood** [comment]
https://drive.google.com/file/d/1kkUv5__5dyC4YUkptdH4d7h_TpMZrnxs/view?usp=drivesdk

Will this share link work?

**Comment by ajmacdonald** [comment]
Yes, that worked.
I see what the issue is and it has been fixed, but the code on https://voyant-tools.org/ has not been updated yet.
If you're interested in experimenting with Spyral, you can try the beta version at https://beta.voyant-tools.org/spyral/
It is much more current, but (again) under heavy development.
