### ISSUE TITLE
"This tool has exceeded the maximum run time and has returned partial results."

### ISSUE THREAD

**Issue by brimwats** [voyanttools/Voyant#39]
Trying to use the collacations tool on a 1mb text file. Voyant has 12000MB to work with. 

I am not sure what is useful for logs, but  here is the most recent info: https://pastebin.com/fKa9jJnR

**Comment by ajmacdonald** [comment]
Some tools (like correlations) can take a long time to run so I've put timeout limits in place so that the server is not overwhelmed. Since you're running your own instance, you can tweak these limits by modifying this file: https://github.com/voyanttools/trombone/blob/master/src/main/resources/org/voyanttools/trombone/limits/config.properties

On your instance it should be available here: `C:/Users/bri/syncthing/pc/00.%20Program%20Settings/96.%20Voyant/_app/WEB-INF/classes/org/voyanttools/trombone/limits/config.properties`

The values are in milliseconds, so you could try setting `termCorrelationsMaxTime` to `60000`, which would be one minute.

Due to the caching that Voyant performs, you'll need to either recreate your corpus or wipe the local cache. Feel free to email me at voyanttools at gmail for more assistance.

**Comment by brimwats** [comment]
brilliant! I figured it was a config somewhere. appreciate your time!
